server:
  port: 444

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  endpoint:
    gateway:
      enabled: true

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: TRACE
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
  config:
    import: gateway-routes.yml
