management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: TRACE

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

  config:
    import: gateway-routes.yml
