management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
      
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: TRACE
          
spring:
  config:
    import:
      - "https://raw.githubusercontent.com/nish22ant/invest-configs/gateway/gateway-routes.yml"
