management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
      
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: TRACE
          
spring:
  config:
    import: classpath:/gateway-routes.yml
