spring:
  cloud:
    gateway:
      routes:
        - id: discovery-service
          uri: lb://discovery-service
          predicates:
            - Path=/discovery-service/**
          filters:
            - StripPrefix=1
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users
            filters:
              - RemoveRequestHeader=Cookie
        - id: address-service
          uri: lb://address-service
          predicates:
            - Path=/api/v1/address
          filters:
            - RemoveRequestHeader=Cookie
