eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      
      
spring:
  datasource:
      url: jdbc:postgresql://localhost:5432/user_service
      username: postgres
      password: root
      
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  config:
    import:
    - "https://raw.githubusercontent.com/nish22ant/invest-configs/user-service/resilience4j.yml"
management:
  endpoints:
    web:
      exposure:
        include: "*"
